name = "contraptioncart-paypal-orders"
main = "worker.js"
compatibility_date = "2024-11-01"
workers_dev = true

# Set with: npx wrangler secret put PAYPAL_CLIENT_ID
#            npx wrangler secret put PAYPAL_CLIENT_SECRET
[vars]
PAYPAL_ENV = "live"
